all:
	lazbuild --build-mode= *.lpi

clean:
	if test -d lib ; then rm  -rf lib ;  fi
	if test -f LabsTweakTools  ; 	then rm LabsTweakTools  ;  fi
	if test -f out.txt ; then rm out.txt ; fi
	if test -f err.txt ; then rm err.txt ; fi




